### ISSUE TITLE
Fix: Failed to load plugin '@typescript-eslint'

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/eslint-config-nimble#56]
## Issue

When we just using the `@nimblehq/eslint-config-nimble-core` by following the README we receives the error

```
Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @nimblehq/eslint-config-nimble-core » /home/runner/work/rails-templates/rails-templates/rails_templates/node_modules/@nimblehq/eslint-config-nimble-core/lib/rules/typescript.js': Cannot find module 'typescript'
```

## Expected

The README should be up-to-date that allow the developer could use the `@nimblehq/eslint-config-nimble-core` straightforward and there is no `Failed to load plugin '@typescript-eslint' declared in '.eslintrc` error.

## Steps to reproduce

1. Create a new Rails project
2. Update the Eslint version
3. Yarn install

**Comment by mosharaf13** [comment]
One of the solutions that fixes this issue is adding `typescript` and `prettier@2.80` as dependencies on package.json. Using `prettier@3` also works but it requires `"eslint-plugin-prettier": "^5"`.

However, if we want to use it in [rails_templates](https://github.com/nimblehq/rails-templates),  we have to replace `require` with `import` in [build.js](https://github.com/nimblehq/rails-templates/blob/develop/.template/variants/web/app/javascript/build.js) like below

```
import esbuild from 'esbuild';

esbuild
  .build({
    entryPoints: [
```

This solution solves the issue but I am not sure if it's the best solution ( two bulky dependency 🏋🏼‍♂️  ). Any suggestions on what other ways I should look into to fix the issue would be really helpful @andyduong1920 @carryall

**Comment by malparty** [comment]
@carryall would you have time to work on this one? Or should I try to assign it to someone else? 👀 

Thanks 🙏

**Comment by sanG-github** [comment]
Our Rails application, which originates from the Rails template, currently operates `without TypeScript integration`. Mosharaf proposed that incorporating the `typescript` package would effectively address this.

However, the inclusion of the `typescript` package, while resolving the workflow issue, poses challenges due to `its substantial weight and redundancy` within our application. Upon reviewing the structure and guidelines outlined in `@nimblehq/eslint-config-nimble-core`:

<img width="266" alt="image" src="https://github.com/nimblehq/eslint-config-nimble/assets/63148598/71618ec4-1236-4785-b15c-5713bc43832c">


It appears more pragmatic to segregate `typescript` into a distinct package, separating it from the current `core` configuration.
